"""Presentation helpers for the Stage 16 audit and confirmation ledgers."""

from __future__ import annotations

from pathlib import Path
from typing import Mapping

import numpy as np
import pandas as pd


def _fmt(value: object, digits: int = 6) -> str:
    if value is None or (isinstance(value, float) and not np.isfinite(value)):
        return "unavailable"
    if isinstance(value, (float, np.floating)):
        return f"{float(value):.{digits}f}"
    return str(value)


def _markdown_table(frame: pd.DataFrame, max_rows: int = 25) -> str:
    if frame is None or frame.empty:
        return "No observations were available."
    value = frame.head(max_rows).copy()
    for column in value.columns:
        if pd.api.types.is_float_dtype(value[column]):
            value[column] = value[column].map(lambda item: _fmt(item, 6))
    headers = [str(column) for column in value.columns]
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in value.itertuples(index=False, name=None):
        cells = []
        for item in row:
            if item is None or (isinstance(item, float) and not np.isfinite(item)):
                cells.append("unavailable")
            else:
                cells.append(str(item).replace("|", "\\|"))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_results_markdown(
    path: Path,
    *,
    manifest: Mapping[str, object],
    model_summary: pd.DataFrame,
    stock_summary: pd.DataFrame,
    comparison: pd.DataFrame,
    hac: pd.DataFrame,
    bootstrap: pd.DataFrame,
    edge_stability: pd.DataFrame,
    forecast_status: str,
) -> None:
    """Write a self-contained, honest run report."""

    status = str(manifest.get("status", forecast_status))
    lines = [
        "# Stage 16 OOS Results",
        "",
        f"Protocol version: `{manifest.get('protocol_version', 'unknown')}`.  Protocol hash: `{manifest.get('protocol_hash', 'unknown')}`.",
        f"Run mode: `{manifest.get('mode', 'unknown')}`.  Status: **{status}**.",
        f"Freeze timestamp: `{manifest.get('freeze_timestamp_utc', 'unknown')}`.  Last data examined: `{manifest.get('last_data_examined', 'unknown')}`.",
        "",
        "## Execution status",
        "",
        "This report distinguishes the historical pseudo-out-of-sample replay from the prospective confirmation cohort. Historical origins were generated by a walk-forward procedure, but the historical sample had already been examined during model development and is not an untouched holdout. Prospective rows are immutable at issuance and are scored only after their target outcome becomes available.",
        "",
        f"The forecast ledger status is `{forecast_status}`. The prospective confirmation endpoint is a predeclared 252 exchange-session horizon; absent eligible post-freeze outcomes are reported as awaiting future data rather than imputed or backfilled.",
        "",
        "## Matched forecast evidence",
        "",
        _markdown_table(comparison),
        "",
        "The primary comparison is the date-level mean of the stock-panel QLIKE differential, Network HAR minus own HAR. Negative values favor Network HAR. Raw QLIKE levels are not ranked across different factor-window targets because each window constructs a different residual target.",
        "",
        "### Model summaries",
        "",
        _markdown_table(model_summary),
        "",
        "### Secondary per-stock summaries",
        "",
        _markdown_table(stock_summary),
        "",
        "## Uncertainty",
        "",
        "The Bartlett-HAC values are asymptotic diagnostics for the date-indexed loss differential. The moving-block bootstrap resamples shared date indices across the full stock panel; its percentile interval describes the observed forecasting loss series and does not propagate every source of factor estimation, tuning, or historical researcher selection uncertainty.",
        "",
        _markdown_table(hac),
        "",
        _markdown_table(bootstrap),
        "",
        "Per-stock results are secondary and are reported with both Benjamini–Hochberg and Holm adjustments when available. The one-standard-error penalty rule is a selection heuristic based on three chronological folds, not an inferential confidence interval.",
        "",
        "## Network diagnostics",
        "",
        _markdown_table(edge_stability),
        "",
        "Edge selection frequency, conditional bootstrap selection frequency, and predictive improvement are distinct quantities. Directed edges are conditional predictive relationships and do not establish structural causation or tradable alpha. Conditional edge bootstrap output, when requested, is conditional on generated features and the observed penalty.",
        "",
        "## Methodological scope and limitations",
        "",
        "The target is the realized variance of factor-adjusted returns, constructed from valid non-overlapping five-minute bins. The logarithm is used for the HAR response and features, while the observed positive variance is used directly for QLIKE scoring. The one-session forecast clock ends at the exchange close of origin session d and precedes the open of session d+1.",
        "",
        "The HAR feature variant follows the daily, weekly, and monthly cascade motivation in Corsi (2009), but uses the repository's mean-of-log convention. QLIKE and the treatment of imperfect realized-volatility proxies follow the robustness concerns in Patton (2011). Predictive-procedure comparison is interpreted conservatively in light of Giacomini and White (2006), because the fitted models are nested, expanding, and penalized.",
        "",
        "References: [Corsi (2009)](https://academic.oup.com/jfec/article-abstract/7/2/174/856522), [Patton (2011)](https://doi.org/10.1016/j.jeconom.2010.03.034), and [Giacomini and White (2006)](https://doi.org/10.1111/j.1468-0262.2006.00718.x).",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_figures(
    scored: pd.DataFrame,
    comparison: pd.DataFrame,
    bootstrap: pd.DataFrame,
    edge_stability: pd.DataFrame,
    *,
    out_dir: Path,
) -> None:
    """Write compact, deterministic figures when plotting dependencies exist."""

    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return

    out_dir.mkdir(parents=True, exist_ok=True)
    if scored is not None and not scored.empty:
        value = scored[scored["score_status"] == "scored"].copy()
        daily = (
            value[value["model"].isin(["own_har", "network_har_l1_1se"])]
            .groupby(["spec_name", "target_date", "model"], as_index=False)["qlike"]
            .mean()
            .pivot(index=["spec_name", "target_date"], columns="model", values="qlike")
            .reset_index()
        )
        if {"own_har", "network_har_l1_1se"}.issubset(daily.columns):
            daily["loss_difference"] = daily["network_har_l1_1se"] - daily["own_har"]
        differential = daily.dropna(subset=["loss_difference"]).loc[
            :, ["spec_name", "target_date", "loss_difference"]
        ]
        if not differential.empty:
            fig, ax = plt.subplots(figsize=(10, 5))
            for spec_name, group in differential.groupby("spec_name"):
                group = group.sort_values("target_date")
                ax.plot(group["target_date"], group["loss_difference"].cumsum(), label=str(spec_name))
            ax.axhline(0.0, color="black", linewidth=0.8)
            ax.set_title("Cumulative Network HAR minus own-HAR QLIKE")
            ax.set_ylabel("Cumulative QLIKE differential")
            ax.legend(frameon=False)
            fig.autofmt_xdate()
            fig.tight_layout()
            fig.savefig(out_dir / "oos_cumulative_qlike_difference.png", dpi=150)
            plt.close(fig)

    if comparison is not None and not comparison.empty and {"spec_name", "network_qlike_minus_own"}.issubset(comparison.columns):
        fig, ax = plt.subplots(figsize=(9, 4))
        ordered = comparison.sort_values("network_qlike_minus_own")
        ax.bar(ordered["spec_name"].astype(str), ordered["network_qlike_minus_own"])
        ax.axhline(0.0, color="black", linewidth=0.8)
        ax.set_title("Date-aggregated QLIKE differential by specification")
        ax.set_ylabel("Network minus own HAR")
        ax.tick_params(axis="x", rotation=25)
        fig.tight_layout()
        fig.savefig(out_dir / "oos_qlike_comparison.png", dpi=150)
        plt.close(fig)

    if bootstrap is not None and not bootstrap.empty:
        value = bootstrap.copy()
        if {"spec_name", "observed_mean_difference", "bootstrap_ci_low", "bootstrap_ci_high"}.issubset(value.columns):
            fig, ax = plt.subplots(figsize=(9, 4))
            x = np.arange(len(value))
            means = value["observed_mean_difference"].to_numpy(dtype=float)
            low = means - value["bootstrap_ci_low"].to_numpy(dtype=float)
            high = value["bootstrap_ci_high"].to_numpy(dtype=float) - means
            ax.errorbar(x, means, yerr=np.vstack([low, high]), fmt="o")
            ax.axhline(0.0, color="black", linewidth=0.8)
            ax.set_xticks(x, value["spec_name"].astype(str), rotation=25, ha="right")
            ax.set_title("Moving-block bootstrap intervals")
            ax.set_ylabel("Mean QLIKE differential")
            fig.tight_layout()
            fig.savefig(out_dir / "oos_bootstrap_intervals.png", dpi=150)
            plt.close(fig)
